### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by thagxt** [debba/greenpass-covid19-qrcode-decoder#3]
The demo site isn't working. 

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by debba** [comment]
I cannot see any errors on demo website.
Do you still continue to have internal server error?

**Comment by thagxt** [comment]
Yes, I've tried with 2 different images and I get `500 Internal server error`. This is the [image in question](https://i.imgur.com/0ghkkF4.png)

I've also tried with [this one](https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/examples) and it's working fine with this image.

**Comment by debba** [comment]
yeah, you're right.
I just fixed the bug.
Let me know if now it works as expected.

**Comment by thagxt** [comment]
Yes, it is working now. Thank you. 

It was because of the Cyrillic chars?

**Comment by thagxt** [comment]
Sorry, one more question. would it be possible to have also the json schema output in the web demo along the formatted one?

**Comment by debba** [comment]
Maybe it can depends on cyrillic chars .

Pull requests and stars are always welcome ;)
